### PR TITLE
Update TOPP parameter section

### PR DESCRIPTION
**Pull request by axelwalter**
### **User description**
This update addresses issues #85 and #84.

1) TOPP tool input sections are structured based on the full parameter name (e.g. all parameter belonging to section:subsection are grouped together. If a section description is available it is displayed as help text. Removed the option to display full parameter names on the widget itself (redundant with this solution).

2) Option to display TOPP tool name.

3) Added a streamlit error box if a TOPP tool was not found instead.

Screenshot From 2024-10-22 10-57-38

___

### **PR Type**
enhancement, bug fix

___

### **Description**
- Added error handling to display a Streamlit error message if a specified TOPP tool is not found, improving user feedback.
- Enhanced the `input_TOPP` method to display tool names and organize parameters into subsections, improving the user interface.
- Improved code readability and maintainability by restructuring long lines and adding comments.
- Updated file upload and directory selection logic to handle various file types and user preferences more effectively.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>StreamlitUI.py</strong><dd><code>Enhance TOPP tool parameter handling and error messaging</code>&nbsp; </dd></summary>
<hr>

src/workflow/StreamlitUI.py

<li>Added error handling for missing TOPP tools with descriptive error <br>messages.<br> <li> Enhanced parameter input handling by introducing subsections and <br>displaying tool names.<br> <li> Improved code formatting and readability by restructuring long lines <br>and adding comments.<br> <li> Updated logic for handling file uploads and directory selections.<br>

</details>

  </td>
  <td><a href="https://github.com/OpenMS/streamlit-template/pull/86/files#diff-d2d8b6f64f15e9961120b170f519cff4a534717079fb0ab30a47afffa4a4daa7">+232/-148</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by jcharkow** [comment]
Much better than before however still facing a few issues. Note I will be updating OpenSWATH parameters so hopefully that helps make things cleaner as well. 

1. Seems that parameters specifying output files are missing? Not sure if this is done on purpose? E.g. out_osw, Debugging:irt_mzml etc.
2. A lot of the different subsections are combined into a single section and not split into different sections?  E.g. Scores section and EMG scoring section parameters are all combined.

**Review by jcharkow — APPROVED** [review]
Code looks good see comments in PR

**Comment by jcharkow** [comment]
Another TOPP tool which would be good to test out is ProteomicsLFQ. With this and OpenSwathWorkflow it might be worth it to separate subsections into tabs because there are so many options. However, I am not sure how many parameters of proteomicsLFQ are used in practice

**Comment by axelwalter** [comment]
Thanks for the feedback!

1) Yes output file parameters are missing intentionally, since they are not handled by the GUI user.

2) Good point, this is determined in the TOPP tool C++ code. The parameter nesting should be modified there.

I really like the idea with tabs for larger tools, just added a commit with a new option accordingly.

image

**Pull request merged**
